# Generated by Django 3.0.7 on 2020-07-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='last',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='last',
            name='date',
            field=models.DateField(verbose_name='The date you seen Finch'),
        ),
        migrations.AddField(
            model_name='finch',
            name='trees',
            field=models.ManyToManyField(to='main_app.Tree'),
        ),
    ]
